apiVersion: v2
appVersion: 2.11.5
description: A Helm chart for multicluster-engine
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:3ee3769e32a21e4108cb1e0f2263fb6aa696a8bcff2207311a0fbeb59f8da9df
type: application
version: 2.11.5
